name: st_action

on:
  workflow_call:
    inputs:
      st_type:
        required: true
        type: string
      st_package:
        required: false
        type: string
        default: 'st_cov_*.tar.gz'
      language:
        required: false
        type: string
        default: 'cpp'
      image_version:
        required: true
        type: string

jobs:
  JOB_st:
    name: ST
    steps:
      - name: Checkout
        identifier: process_checkout_st
        uses: checkout
        with:
          ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          allow-unsafe-pr-checkout: true

      - name: download
        uses: obs-download
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          key: |
            ${{ env.obs_path }}/pr_filelist.txt
            ${{ env.obs_path }}/pr_filelist_mod.txt
            ${{ env.obs_path }}/tensorflow_st.sh
          path: ${{ steps.process_checkout_st.outputs.path }}

      - name: redis-cache
        uses: cann/.gitcode/actions/redis-cache@master

      - name: st_acc
        identifier: st
        run: |
          export WORKSPACE=${{ steps.process_checkout_st.outputs.path }}
          cd ${{ steps.process_checkout_st.outputs.path }}
          export GIT_TARGET_BRANCH=${{ env.TARGET_BRANCH }}
          export TF_ST_TYPE=${{ inputs.st_type }}
          export ASCEND_3RD_LIB_PATH=/home/jenkins/opensource
          export ASCEND_INSTALL_PATH=/home/jenkins/Ascend/cann
          export ASCEND_HOME_PATH=/home/jenkins/Ascend/cann
          export ASCEND_CUSTOM_PATH=/home/jenkins/Ascend/cann
          bash tensorflow_st.sh

      - name: ST_Cov
        identifier: ut_cov
        uses: cann/.gitcode/actions/ut-cov-report@master
        with:
          ut_process: 'ut_cov'
          workspace: ${{ steps.process_checkout_st.outputs.path }}
          language: ${{ inputs.language }}
          ut_type: ${{ inputs.st_type }}
          target_branch: ${{ env.TARGET_BRANCH }}
          git_token: ${{secrets.GIT_TOKEN}}

      - name: upload
        uses: obs-upload
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          artifact-path: "${{ steps.process_checkout_st.outputs.path }}/${{ inputs.st_package }}"
          object-prefix: ${{ env.obs_path }}/
    if: "${{ default() }}"
    runs-on: [dedicate-hosted, x64, xlarge]
    container:
      image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ inputs.image_version }}
